### PR TITLE
Fix request/response logging for SetDoNotParseResponse(true)

### PR DESCRIPTION
**Pull request by kon3gor**
Bug fix for #829 

## Changes
- `responseLogger` is not middleware anymore for consistency reasons
- `responseLogger` is now being called whenever `execute` exits
- Parameter name in `SetDoNotParseResponse` has been changed to `notParse`

### CODE REVIEW

**Review by jeevatkm — CHANGES_REQUESTED** [review]
@kon3gor Thanks for creating a PR. The code updates LGTM, can you please check test failures and code conflicts?

**Comment by kon3gor** [comment]
@jeevatkm Tests and merged conflicts are fixed now🫡

**Comment by jeevatkm** [comment]
@kon3gor Thanks for taking care of the tests. It seems the `errors.Join` method is causing a failure on tests. Since it's added in go1.20, but resty supports go min version 1.19

Please see https://github.com/go-resty/resty/pull/836/checks

**Comment by kon3gor** [comment]
@jeevatkm Hi! I've removed `erros.Join` and replaced it with the self-made replica. Also made some logic fixes for logging logging errors.

**Comment by kon3gor** [comment]
@jeevatkm Looks like `errors.Is` logic has been changed for joinError support. In go1.19 there was no `Unwrap []error` interface, that why my custom joinErr doesn't work. I'll change logic a bit to match this old behaviour

**Comment by jeevatkm** [comment]
@kon3gor Okay, please let me know when you are done. 

Also, please add attribution to the code for the method `Join`.
```
// Code obtained from `golang:src/errors/join.go` to backfill until Resty go minimum version gets updated to go1.20
// TODO: Remove this Join-related code.
```

**Comment by jeevatkm** [comment]
@kon3gor I was giving it a second thought on the `go` minimum version.  Let's update the go minimum version to `go1.20`.

Please update `go.mod` and GitHub CI actions files. Then, you can work on the logic update in line with the `go1.20` and above version.

**Review by jeevatkm — APPROVED** [review]
@kon3gor Thanks for updating PR and test cases.

**Pull request merged**
