### PR TITLE
Enhance buildCurlRequest for unit test

### PR DESCRIPTION
**Pull request by yaziedda**
Hacktoberfest

### CODE REVIEW

**Review by jeevatkm — CHANGES_REQUESTED** [review]
@yaziedda Thanks for creating PR. 

I can't see an enhancement in the `util_curl.go`; if you're interested in adding a unit test, it would be appreciated.

Can you please revert the change in `util_curl.go`?

**Comment by yaziedda** [comment]
> @yaziedda Thanks for creating PR.
> 
> I can't see an enhancement in the `util_curl.go`; if you're interested in adding a unit test, it would be appreciated.
> 
> Can you please revert the change in `util_curl.go`?

But for add unit test need improve `util_curl.go` because function buildCurlRequest not give consistent response like double indent after domain. Example :
Expected :
`curl -X GET -H 'Authorization: Bearer token' -H 'Content-Type: application/json' http://example.com`
Actual from existing `util_curl.go`
`curl -X GET -H 'Authorization: Bearer token' -H 'Content-Type: application/json'  http://example.com`

Screenshot from 2024-10-09 11-12-30
Left : My enhance code
Right : From existing code

**Review by jeevatkm — APPROVED** [review]
@yaziedda I see, thanks for the details.

**Comment by jeevatkm** [comment]
@yaziedda, I just noticed this. Can you please move the unit test to this file `curl_cmd_test.go`?

**Comment by yaziedda** [comment]
> @yaziedda, I just noticed this. Can you please move the unit test to this file `curl_cmd_test.go`?

I’ve already changed it to curl_cmd_test.go.

**Review by jeevatkm — APPROVED** [review]
Thanks for correcting it @yaziedda

**Comment by yaziedda** [comment]
You're welcome, can we merge this PR @jeevatkm ?

**Pull request merged**
