### PR TITLE
improve: support js,wasm

### LINKED ISSUE #610: Protocol not available when updating from go 1.17 to 1.19
I'm running resty in a wam application

I got this error with default example : 

```
Error: Get "http://httpbin.org/get": dial tcp: lookup httpbin.org: Protocol not available
wasm_exec.js:19 Response Status Code: 0
wasm_exec.js:19 Response Status: 
wasm_exec.js:19 Response Body: 
wasm_exec.js:19 Response Time: 400.128µs
```

https://gitlab.com/c1560/cryptofiscafacile/-/merge_requests/824

I have tested http.get successfully

### PR DESCRIPTION
**Pull request by shynome**
those code copy from `/go/src/net/http/transport_default_other.go`

closes #610

### CODE REVIEW

**Review by jeevatkm — CHANGES_REQUESTED** [review]
@shynome Can you please add test case?

**Comment by shynome** [comment]
I'm sorry, I don't have time to add test case because I don't use resty anymore.
now I just use http client with some function wrap

as you can see, those code is copy from golang std library `net/http/transport_default_other.go`

**Comment by jeevatkm** [comment]
@shynome Thanks for getting back. I see; I will take it up later on.

**Comment by jeevatkm** [comment]
Ref: https://github.com/golang/go/blob/master/src/net/http/transport_default_wasm.go

**Review by jeevatkm — APPROVED** [review]

**Pull request merged**
