### PR TITLE
Option to close connection for each HTTP request

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <aanm90@gmail.com>

### CODE REVIEW

**Comment by jeevatkm** [comment]
@aanm Thanks for the PR.

Technically there is no leak as per golang core.  Below note taken from golang godoc-
```go
// For client requests, setting this field prevents re-use of
// TCP connections between requests to the same hosts, as if
// Transport.DisableKeepAlives were set.
Close bool
```

So there is no issue with `go-resty` library. I will be renaming the PR subject.

----

I would say it up to developer or user choose the behavior they need. My recommendation is to expose some sort setter method to `opt-in` if they want to close connection for each request and defaults to false (also same as golang core).

your thoughts?

**Comment by aanm** [comment]
@jeevatkm True, on my use case all connection were for the same host but with multiple resty clients. Setting that option to true dropped the number of connections open by 70%. I'll think on something an make it as an option. Any ideas where it would be the best place to put it?

**Comment by jeevatkm** [comment]
You have specific use case. No issues. Best place is to -

* Create a `field` called `closeConnection` after `mutex` [field](https://github.com/go-resty/resty/blob/master/client.go#L93)
* Add `SetCloseConnection` for client struct like 
   * `func (c *Client) SetCloseConnection(close bool) *Client`
   * Please add nice godoc documentation, so user can understand the purpose
* Initialize explicitly on client creation after `mutex` [field](https://github.com/go-resty/resty/blob/master/default.go#L39) like `closeConnection: false`
* Also please add `SetCloseConnection` method to `default.go` like you did in previous PR

finally assign in it the request (you already pick spot for this PR, but small change):
```go
r.RawRequest.Close = c.closeConnection
```

**Comment by jeevatkm** [comment]
Test case please and watch out travis ci build.

**Comment by aanm** [comment]
@jeevatkm ping

**Pull request merged**
