### PR TITLE
Add Request.SetContext

### PR DESCRIPTION
**Pull request by ei-grad**
Implements #44

### CODE REVIEW

**Comment by jeevatkm** [comment]
@ei-grad Thanks for your contribution. 

Yes this feature only supported Go 1.7 and above. So we may have to limit this option. Let me have a look.

**Comment by jeevatkm** [comment]
@ei-grad I have quick question for this PR.

To achieve this PR to work properly, following needs to be done:
* Please branch out fresh, since code quality improvements applied in `master` brach
* We have to take advantage of Go build constraints [reference](https://golang.org/pkg/go/build/)
* Create two files for `type Request struct` with definition for `go1.7 & greater`, `go1.6 & below` and implementation will be separate file which is common part
* And test cases accordingly

This approach is compatible with all Go versions.

Would you like like to try and send PR?

**Comment by ei-grad** [comment]
Yep, I'll do that :).

**Comment by ei-grad** [comment]
@jeevatkm done

**Pull request merged**
