### PR TITLE
feat: add `Clone` method for Request

### LINKED ISSUE #718: Add clone method in `Request`
### Discussed in https://github.com/go-resty/resty/discussions/588

<div type='discussions-op-text'>

<sup>Originally posted by **shotamakino** October 11, 2022</sup>
Hi, thank you for this great package!

I am trying to clone a `Request` instance in order to reuse it again with a different set of query parameters (for pagination). I was wondering if there's some kind of support for a `Clone` method similar to https://pkg.go.dev/net/http#Request.Clone?
</div>

### PR DESCRIPTION
**Pull request by tttturtle-russ**
Close #718

### CODE REVIEW

**Review by jeevatkm — CHANGES_REQUESTED** [review]
@tttturtle-russ Thanks for creating a PR. Can you cover missing test case coverage?
See here - https://github.com/go-resty/resty/pull/847/checks?check_run_id=29887899895

**Comment by tttturtle-russ** [comment]
I fixed it in commit 15f991239684edda1238c53af307c2a26b20e7b0, it may need another coverage check.

**Comment by jeevatkm** [comment]
@tttturtle-russ updated run see here - https://github.com/go-resty/resty/pull/847/checks?check_run_id=29962204508

Also, you could see the coverage on your local.
Run test 
```
go test ./... -race -coverprofile=coverage.out -covermode=atomic -coverpkg=./...
```
See coverage HTML
```
go tool cover -html=coverage.out
```

**Review by jeevatkm — CHANGES_REQUESTED** [review]
@tttturtle-russ Thanks for the test coverage. Can you correct the bullet point formatting in the godoc?

It is not correctly displayed:
Screenshot 2024-09-12 at 7 57 41 AM

**Comment by tttturtle-russ** [comment]
@jeevatkm Documentation looks fine now.
image

**Review by jeevatkm — APPROVED** [review]
@tttturtle-russ Thanks for correcting godoc.

**Pull request merged**
