### PR TITLE
Conditional retry

### PR DESCRIPTION
**Pull request by dmiller113**
Added the ability to add conditions in which to actually retry instead of only on returned errors from the response. This allows you to retry you request again in the case of bad responses in addition to retrying based upon response status codes.

### CODE REVIEW

**Comment by dmiller113** [comment]
Depends on #35.

**Comment by jeevatkm** [comment]
This is nice. I have went through the changes, it seems you have taken implementation from #35 and then added conditional retry ability.

I have suggestion here. 

Can you please hold on for merging #35 (will do as soon as a get a time) and then branch out & add yours? In this way both contributors changes will come to resty separately.

I would like to appreciate both contribution.

**Comment by jeevatkm** [comment]
@dmiller113 I have merged #35 to master. Please branch out master and add your conditional retry. I appreciate your efforts.

I'm closing this one.

**Comment by jeevatkm** [comment]
@dmiller113 awaiting your PR, Thanks.

**Comment by jeevatkm** [comment]
@dmiller113 I hope you don't mind, if incorporate your contribution into resty and release your contribution.

**Pull request closed without merging**
