### PR TITLE
WIP: Allow setting any `http.RoundTripper` as transport

### PR DESCRIPTION
**Pull request by bak1an**
Proper doc and test coverage is in progress...

### CODE REVIEW

**Comment by jeevatkm** [comment]
@bak1an Thank you for the updates.

**Comment by jeevatkm** [comment]
@bak1an Hope you're doing well. Any updates on this feature?

**Comment by bak1an** [comment]
@jeevatkm Not yet, will try to wrap it up this weekend. Thanks!

**Comment by jeevatkm** [comment]
@bak1an Thanks, please let me know, if you need a hand.

**Comment by jeevatkm** [comment]
Closing this PR in-favor of #91

**Pull request closed without merging**
