### PR TITLE
Update log level to warning for errors within retry block

### LINKED ISSUE #561: Warn-level logging on retries attempts
Current implementation of (r *Request) Execute(method, url string) (*Response, error) uses Backoff function with hardcoded attempts errors log on Error level:

`r.client.log.Errorf("%v, Attempt %v", err, r.Attempt)`

With enabled retry feature it may be unnecessary for someone to log unsuccessful attempts on Error level. Desired approach would be to log attempts errors on Warning level and only log on Error level if all retries are exceeded with no success.

Can it be achieved with current versions of resty?

Can this behavior be configurable? Maybe even add custom callbacks to handle retry errors?

### PR DESCRIPTION
**Pull request by sandyydk**
Closes #561
Closes #554

### CODE REVIEW

**Comment by sandyydk** [comment]
This fixes the issue
https://github.com/go-resty/resty/issues/561

@jeevatkm

**Review by jeevatkm — CHANGES_REQUESTED** [review]
@sandyydk Thanks for your PR and contribution. I'm sorry for the delayed attention on the PR.
Can you resolve the code conflicts?

**Comment by sandyydk** [comment]
Sure will update this. Thanks for the response.

**Comment by jeevatkm** [comment]
@sandyydk Just wanted to check. Are you planning to update this PR? if not let me know, I will take it up and prepare for next release.

**Comment by sandyydk** [comment]
> @sandyydk Just wanted to check. Are you planning to update this PR? if not let me know, I will take it up and prepare for next release.

@jeevatkm Sorry for the delayed response. Resolved the conflicts. Can you take a look now? Thanks.

**Review by jeevatkm — CHANGES_REQUESTED** [review]
@sandyydk Thanks for you PR, appreciated.

**Review by jeevatkm — APPROVED** [review]

**Pull request merged**
