### PR TITLE
refactor(retry.sleepDuration): :recycle: extract jitterBackoff function

### PR DESCRIPTION
**Pull request by ninedraft**
Refactor sleepDuration function and use local random generatpr

### CODE REVIEW

**Comment by ninedraft** [comment]
@jeevatkm if you are not going to take this MR, please write. This will not offend me at all, I will just try to look for other places in your project where I could be useful!

**Comment by jeevatkm** [comment]
Hello @ninedraft it's not like that. I really appreciate your contribution. Lately, I have been busy with a couple of projects in my day jobs. I'm not getting enough time. In the upcoming days, it will be alright. I will look at this PR this week. Thanks again!

**Review by jeevatkm — APPROVED** [review]
@ninedraft Thanks for your PR and improving Resty.
I'm really sorry for the delay, due to personal reasons.

**Comment by ninedraft** [comment]
thx!

**Pull request merged**
